# Generated by Django 5.1.5 on 2025-02-09 08:22

import django.core.validators
import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(help_text='A valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employment_type',
            field=models.CharField(choices=[(None, '--Please choose--'), ('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract work')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='start_date',
            field=models.DateField(help_text='The earliest date you can start working.', validators=[jobs.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='website',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
